# docker-compose.yml

version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://dentall_rmm2_user:ULoPI4NBThHB77kWvua20vkQ61GuHNgF@dpg-claj19rmot1c7392cnvg-a.frankfurt-postgres.render.com/dentall_rmm2
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
  
  
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: app_db
  #     POSTGRES_USER: app_user
  #     POSTGRES_PASSWORD: password
  # # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"